batch_size: 8
data: empiar10028
decoder_lr: 0.05
encoder_lr: 0.0001
epochs_amortized: 15
epochs_unamortized: 15
num_rotations: 15
path_to_checkpoint: none
pose_iters: 5
prior: 'false'
r: 1.0
rot_lr: 0.05
space: hartley
unamortized_decoder_lr: 0.002
uninvert_data: false
vol_iters: 1
