amortized_method: split_reg
batch_size: 16
data: hsp
data_type: random_membrane_w_wobble
decoder_lr: 0.01
encoder_lr: 0.0005
epochs_amortized: 10
epochs_pre_unamortized: 0
epochs_unamortized: 0
num_rotations: 1
optimizable_angles:
- true
- true
- false
path_to_checkpoint: none
pose_iters: 5
pose_lr: 0.01
pre_unamortized_decoder_lr: 0.003
pre_unamortized_rot_lr: 0.02
prior: 'false'
r: 1.0
rot_lr: 0.05
space: hartley
unamortized_decoder_lr: 0.1
uninvert_data: false
update_hyperparams: false
vol_iters: 4
w1: 0
w2: 0
