mrc: '/h/bizigerd/semi-amortized-cryoem_2/synthetic_data/cryosparc_P179_J3366_class_00_final_volume (6).mrc'
resolution: 4.02
sidelen: 128
num_projs: 6116
snr: 1
power_signal: 0.1
ctf_precompute: true
output_dir: '/datasets/empiar/vatpase_synth_restricted'