amortized_method: in_membrane
batch_size: 64
data_type: real
decoder_lr: 0.05
encoder_lr: 0.00005
in_membrane_lr: 0.005
epochs_amortized: 15
epochs_unamortized: 0
heads: 9

partial_prior: true


vol_rep: explicit

big_dataset: False

partial_prior: True


path_to_checkpoint: none
pose_iters: 5
prior: 'false'
r: 1.0
rot_lr: 0.05
space: hartley
unamortized_decoder_lr: 0.1
uninvert_data: false
vol_iters: 1
w1: 0
w2: 0
